# change the followings to match your Github username and repo name
baseurl: "/mywebsite" # the name of your github repo
url: "https://selsayed25.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Sami Elsayed's Official Website"
description: Elsayed's website using TailwindCSS

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Sami Elsayed
author-bio: Student and Sysadmin  # change to false to hide
author-image: 241408005_551143766213964_3907764800601857433_n.jpg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Bitcoin
  permalink: bitcoin
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: https://twitter.com/
facebook: https://facebook.com/
instagram: https://instagram.com/
github: https://github.com/
linkedin: https://linkedin.com/
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
